config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  
  resources :users do
    resources :costs
  end

  root 'users#index'

end

app/models/cost.rb
class Cost < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :costs, dependent: :destroy 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController

def index
@user = current_user
 @costs = @user.costs
end

def show
	@user = current_user
	@cost = @user.cost(params[:id])
end

def new
	@user = current_user
	@costs = current_user.costs.new
end

def create
	@user = current_user
	@cost = @user.costs.new(cost_params)

	if @cost.save
		redirect_to user_costs_path
	else
	render 'new'
	end
end

def edit
	@user = current_user
	@cost = @user.cost.find(params[:id])
end

def update
	@user = current_user
	@cost = user.costs.find(params[:id])
		if @cost.update(cost_params)
  			redirect_to user_costs_path
  		else
  			render 'edit'
  		end
end

def destroy
	@user = User.find(params[:user_id])
	@cost = @user.costs.find(params[:id])
	@cost.destroy
	redirect_to user_path(@user)
end

private
	def cost_params
		params.require(:cost).permit(:iteam, :cost)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
	@users = User.all
end

def show
  		@user = User.find(params[:id])
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/costs/_form.html.erb
<%= form_for([@user, @user.costs.build]) do |f| %>
  <p>
    <%= f.label :iteam %><br>
    <%= f.text_field :iteam %>
  </p>
  <p>
    <%= f.label :cost %><br>
    <%= f.text_area :cost %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/costs/index.html.erb
<p class='navbar-text pull-right'>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<h1>Costs</h1>
<ul>
 <% @costs.each do |cost| %>
 	<%= cost.iteam %>
 	<%= cost.cost %>
 	<td><%= link_to 'Show', user_cost_path(@user, cost) %></td>
	<td><%= link_to 'Edit', edit_user_cost_path(@user, cost) %></td>
 <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BruBudget</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>


<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<% @users.each do |user| %>
	<%= user.user_name %>
	<%= link_to 'Show Costs', user_path(user) %>
<% end %>

app/views/users/show.html.erb
<%= @user.user_name %>

<h2>Costs</h2>
<%= render @user.costs %>

<h2>Add a Cost</h2>
<%= render 'costs/form' %>